# Generated by Django 3.0.7 on 2025-02-12 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herramientas', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PDFDocument',
        ),
    ]
